-- QuoteReady schema · 0001_init
-- Single demo organisation; no auth in MVP. All UUIDs generated by the DB.

create extension if not exists "pgcrypto";

-- ── organisations ───────────────────────────────────────────────────────────
create table if not exists organisations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

-- ── customers ───────────────────────────────────────────────────────────────
create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid references organisations(id) on delete cascade,
  full_name text not null,
  phone text,
  email text,
  suburb text,
  created_at timestamptz not null default now()
);

-- ── jobs ────────────────────────────────────────────────────────────────────
create table if not exists jobs (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid references organisations(id) on delete cascade,
  customer_id uuid references customers(id) on delete cascade,
  job_type text not null,
  status text not null default 'new',
  readiness_score integer,
  safety_flag boolean not null default false,
  inspection_recommended boolean not null default false,
  enquiry_text text,
  extracted_facts jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_jobs_org on jobs (organisation_id, updated_at desc);
create index if not exists idx_jobs_status on jobs (status);
create index if not exists idx_jobs_updated on jobs (updated_at desc);

-- ── job_evidence ────────────────────────────────────────────────────────────
create table if not exists job_evidence (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references jobs(id) on delete cascade,
  evidence_type text not null, -- enquiry | image | voice_note | manual_note | customer_reply
  storage_path text,
  transcript text,
  source_label text,           -- enquiry_text | image_1 | voice_note_1 ...
  extracted_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_evidence_job on job_evidence (job_id, created_at);

-- ── scope_versions ──────────────────────────────────────────────────────────
create table if not exists scope_versions (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references jobs(id) on delete cascade,
  version_number integer not null,
  readiness_score integer not null,
  status text not null,
  scope jsonb not null,        -- full ScopePack document
  created_by text not null,    -- ai_analysis | voice_update | manual_edit | fallback | seed
  created_at timestamptz not null default now(),
  unique(job_id, version_number)
);
create index if not exists idx_scope_job on scope_versions (job_id, version_number desc);

-- ── message_drafts ──────────────────────────────────────────────────────────
create table if not exists message_drafts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references jobs(id) on delete cascade,
  message_type text not null,  -- request_information | inspection_recommended
  body text not null,
  requests_fields jsonb not null default '[]'::jsonb,
  status text not null default 'draft', -- draft | approved
  approved_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_drafts_job on message_drafts (job_id, created_at desc);

-- ── audit_events ────────────────────────────────────────────────────────────
create table if not exists audit_events (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references jobs(id) on delete cascade,
  actor_type text not null,    -- user | ai | system
  event_type text not null,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_job on audit_events (job_id, created_at desc);

-- ── updated_at trigger ──────────────────────────────────────────────────────
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_jobs_updated_at on jobs;
create trigger trg_jobs_updated_at before update on jobs
  for each row execute function set_updated_at();

-- ── storage buckets (created via SQL for reproducibility) ───────────────────
insert into storage.buckets (id, name, public) values ('job-images','job-images', true)
  on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('voice-notes','voice-notes', false)
  on conflict (id) do nothing;
